/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace ICacheManagerAutomation {
  export type ContractConfigStruct = {
    contractAddress: AddressLike;
    maxBid: BigNumberish;
    enabled: boolean;
    autoActivate: boolean;
    maxActivationCost: BigNumberish;
  };

  export type ContractConfigStructOutput = [
    contractAddress: string,
    maxBid: bigint,
    enabled: boolean,
    autoActivate: boolean,
    maxActivationCost: bigint
  ] & {
    contractAddress: string;
    maxBid: bigint;
    enabled: boolean;
    autoActivate: boolean;
    maxActivationCost: bigint;
  };

  export type UserContractsDataStruct = {
    user: AddressLike;
    contracts: ICacheManagerAutomation.ContractConfigStruct[];
  };

  export type UserContractsDataStructOutput = [
    user: string,
    contracts: ICacheManagerAutomation.ContractConfigStructOutput[]
  ] & {
    user: string;
    contracts: ICacheManagerAutomation.ContractConfigStructOutput[];
  };

  export type ActivationRequestStruct = {
    user: AddressLike;
    contractAddress: AddressLike;
  };

  export type ActivationRequestStructOutput = [
    user: string,
    contractAddress: string
  ] & { user: string; contractAddress: string };

  export type BidRequestStruct = {
    user: AddressLike;
    contractAddress: AddressLike;
  };

  export type BidRequestStructOutput = [
    user: string,
    contractAddress: string
  ] & { user: string; contractAddress: string };
}

export interface CacheManagerAutomationInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "arbWasm"
      | "arbWasmCache"
      | "bidIncrement"
      | "cacheManager"
      | "cacheThreshold"
      | "escrow"
      | "fundBalance"
      | "getContracts"
      | "getContractsPaginated"
      | "getTotalUsersCount"
      | "getUserAtIndex"
      | "getUserBalance"
      | "getUserContracts"
      | "horizonSeconds"
      | "insertContract"
      | "maxActivationsPerIteration"
      | "maxBidsPerIteration"
      | "maxContractsPerUser"
      | "maxUserFunds"
      | "maxUsersPerPage"
      | "minFundAmount"
      | "minMaxBidAmount"
      | "owner"
      | "placeActivations"
      | "placeBids"
      | "removeAllContracts"
      | "removeContract"
      | "renounceOwnership"
      | "setBidIncrement"
      | "setCacheThreshold"
      | "setHorizonSeconds"
      | "setMaxActivationsPerIteration"
      | "setMaxBidsPerIteration"
      | "setMaxContractsPerUser"
      | "setMaxUserFunds"
      | "setMaxUsersPerPage"
      | "setMinFundAmount"
      | "setMinMaxBidAmount"
      | "transferOwnership"
      | "updateContract"
      | "userContracts"
      | "withdrawBalance"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ActivationError"
      | "ActivationPerformed"
      | "ActivationRevertData"
      | "BalanceUpdated"
      | "BidAttempted"
      | "BidDetails"
      | "BidError"
      | "BidIncrementUpdated"
      | "BidPlaced"
      | "CacheThresholdUpdated"
      | "ContractAdded"
      | "ContractAutoActivateUpdated"
      | "ContractMaxActivationCostUpdated"
      | "ContractOperationPerformed"
      | "ContractRemoved"
      | "ContractUpdated"
      | "DebugBidCheck"
      | "DebugMinBidFetch"
      | "HorizonSecondsUpdated"
      | "MaxActivationsPerIterationUpdated"
      | "MaxBidsPerIterationUpdated"
      | "MaxContractsPerUserUpdated"
      | "MaxUserFundsUpdated"
      | "MaxUsersPerPageUpdated"
      | "MinBidCheck"
      | "MinFundAmountUpdated"
      | "MinMaxBidAmountUpdated"
      | "OwnershipTransferred"
      | "Paused"
      | "Unpaused"
      | "UpkeepPerformed"
      | "UserBalanceOperation"
  ): EventFragment;

  encodeFunctionData(functionFragment: "arbWasm", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "arbWasmCache",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "bidIncrement",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cacheManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cacheThreshold",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "escrow", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "fundBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getContracts",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getContractsPaginated",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalUsersCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUserAtIndex",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUserContracts",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "horizonSeconds",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "insertContract",
    values: [AddressLike, BigNumberish, boolean, boolean, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "maxActivationsPerIteration",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "maxBidsPerIteration",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "maxContractsPerUser",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "maxUserFunds",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "maxUsersPerPage",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "minFundAmount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "minMaxBidAmount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "placeActivations",
    values: [ICacheManagerAutomation.ActivationRequestStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "placeBids",
    values: [ICacheManagerAutomation.BidRequestStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "removeAllContracts",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "removeContract",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setBidIncrement",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setCacheThreshold",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setHorizonSeconds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxActivationsPerIteration",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxBidsPerIteration",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxContractsPerUser",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxUserFunds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxUsersPerPage",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMinFundAmount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMinMaxBidAmount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateContract",
    values: [AddressLike, BigNumberish, boolean, boolean, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "userContracts",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawBalance",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "arbWasm", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "arbWasmCache",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bidIncrement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cacheManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cacheThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "escrow", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "fundBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getContracts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getContractsPaginated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalUsersCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserAtIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserContracts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "horizonSeconds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "insertContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxActivationsPerIteration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxBidsPerIteration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxContractsPerUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxUserFunds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxUsersPerPage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minFundAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minMaxBidAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "placeActivations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "placeBids", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeAllContracts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setBidIncrement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCacheThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setHorizonSeconds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMaxActivationsPerIteration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMaxBidsPerIteration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMaxContractsPerUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMaxUserFunds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMaxUsersPerPage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMinFundAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMinMaxBidAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userContracts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawBalance",
    data: BytesLike
  ): Result;
}

export namespace ActivationErrorEvent {
  export type InputTuple = [
    user: AddressLike,
    contractAddress: AddressLike,
    value: BigNumberish,
    reason: string
  ];
  export type OutputTuple = [
    user: string,
    contractAddress: string,
    value: bigint,
    reason: string
  ];
  export interface OutputObject {
    user: string;
    contractAddress: string;
    value: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ActivationPerformedEvent {
  export type InputTuple = [
    user: AddressLike,
    contractAddress: AddressLike,
    version: BigNumberish,
    dataFee: BigNumberish,
    spent: BigNumberish,
    refund: BigNumberish,
    userBalance: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    contractAddress: string,
    version: bigint,
    dataFee: bigint,
    spent: bigint,
    refund: bigint,
    userBalance: bigint
  ];
  export interface OutputObject {
    user: string;
    contractAddress: string;
    version: bigint;
    dataFee: bigint;
    spent: bigint;
    refund: bigint;
    userBalance: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ActivationRevertDataEvent {
  export type InputTuple = [
    user: AddressLike,
    contractAddress: AddressLike,
    data: BytesLike
  ];
  export type OutputTuple = [
    user: string,
    contractAddress: string,
    data: string
  ];
  export interface OutputObject {
    user: string;
    contractAddress: string;
    data: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BalanceUpdatedEvent {
  export type InputTuple = [user: AddressLike, newBalance: BigNumberish];
  export type OutputTuple = [user: string, newBalance: bigint];
  export interface OutputObject {
    user: string;
    newBalance: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BidAttemptedEvent {
  export type InputTuple = [
    user: AddressLike,
    contractAddress: AddressLike,
    bid: BigNumberish,
    success: boolean
  ];
  export type OutputTuple = [
    user: string,
    contractAddress: string,
    bid: bigint,
    success: boolean
  ];
  export interface OutputObject {
    user: string;
    contractAddress: string;
    bid: bigint;
    success: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BidDetailsEvent {
  export type InputTuple = [
    user: AddressLike,
    contractAddress: AddressLike,
    bidAmount: BigNumberish,
    minBid: BigNumberish,
    maxBid: BigNumberish,
    userBalance: BigNumberish,
    success: boolean
  ];
  export type OutputTuple = [
    user: string,
    contractAddress: string,
    bidAmount: bigint,
    minBid: bigint,
    maxBid: bigint,
    userBalance: bigint,
    success: boolean
  ];
  export interface OutputObject {
    user: string;
    contractAddress: string;
    bidAmount: bigint;
    minBid: bigint;
    maxBid: bigint;
    userBalance: bigint;
    success: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BidErrorEvent {
  export type InputTuple = [
    user: AddressLike,
    contractAddress: AddressLike,
    bid: BigNumberish,
    reason: string
  ];
  export type OutputTuple = [
    user: string,
    contractAddress: string,
    bid: bigint,
    reason: string
  ];
  export interface OutputObject {
    user: string;
    contractAddress: string;
    bid: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BidIncrementUpdatedEvent {
  export type InputTuple = [oldValue: BigNumberish, newValue: BigNumberish];
  export type OutputTuple = [oldValue: bigint, newValue: bigint];
  export interface OutputObject {
    oldValue: bigint;
    newValue: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BidPlacedEvent {
  export type InputTuple = [
    user: AddressLike,
    contractAddress: AddressLike,
    bidAmount: BigNumberish,
    maxBid: BigNumberish,
    userBalance: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    contractAddress: string,
    bidAmount: bigint,
    maxBid: bigint,
    userBalance: bigint
  ];
  export interface OutputObject {
    user: string;
    contractAddress: string;
    bidAmount: bigint;
    maxBid: bigint;
    userBalance: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CacheThresholdUpdatedEvent {
  export type InputTuple = [oldValue: BigNumberish, newValue: BigNumberish];
  export type OutputTuple = [oldValue: bigint, newValue: bigint];
  export interface OutputObject {
    oldValue: bigint;
    newValue: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ContractAddedEvent {
  export type InputTuple = [
    user: AddressLike,
    contractAddress: AddressLike,
    maxBid: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    contractAddress: string,
    maxBid: bigint
  ];
  export interface OutputObject {
    user: string;
    contractAddress: string;
    maxBid: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ContractAutoActivateUpdatedEvent {
  export type InputTuple = [
    user: AddressLike,
    contractAddress: AddressLike,
    autoActivate: boolean
  ];
  export type OutputTuple = [
    user: string,
    contractAddress: string,
    autoActivate: boolean
  ];
  export interface OutputObject {
    user: string;
    contractAddress: string;
    autoActivate: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ContractMaxActivationCostUpdatedEvent {
  export type InputTuple = [
    user: AddressLike,
    contractAddress: AddressLike,
    maxActivationCost: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    contractAddress: string,
    maxActivationCost: bigint
  ];
  export interface OutputObject {
    user: string;
    contractAddress: string;
    maxActivationCost: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ContractOperationPerformedEvent {
  export type InputTuple = [
    user: AddressLike,
    contractAddress: AddressLike,
    operation: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    contractAddress: string,
    operation: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    user: string;
    contractAddress: string;
    operation: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ContractRemovedEvent {
  export type InputTuple = [user: AddressLike, contractAddress: AddressLike];
  export type OutputTuple = [user: string, contractAddress: string];
  export interface OutputObject {
    user: string;
    contractAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ContractUpdatedEvent {
  export type InputTuple = [
    user: AddressLike,
    contractAddress: AddressLike,
    maxBid: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    contractAddress: string,
    maxBid: bigint
  ];
  export interface OutputObject {
    user: string;
    contractAddress: string;
    maxBid: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DebugBidCheckEvent {
  export type InputTuple = [
    user: AddressLike,
    contractAddress: AddressLike,
    step: string
  ];
  export type OutputTuple = [
    user: string,
    contractAddress: string,
    step: string
  ];
  export interface OutputObject {
    user: string;
    contractAddress: string;
    step: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DebugMinBidFetchEvent {
  export type InputTuple = [
    contractAddress: AddressLike,
    minBid: BigNumberish,
    success: boolean
  ];
  export type OutputTuple = [
    contractAddress: string,
    minBid: bigint,
    success: boolean
  ];
  export interface OutputObject {
    contractAddress: string;
    minBid: bigint;
    success: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace HorizonSecondsUpdatedEvent {
  export type InputTuple = [oldValue: BigNumberish, newValue: BigNumberish];
  export type OutputTuple = [oldValue: bigint, newValue: bigint];
  export interface OutputObject {
    oldValue: bigint;
    newValue: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MaxActivationsPerIterationUpdatedEvent {
  export type InputTuple = [oldValue: BigNumberish, newValue: BigNumberish];
  export type OutputTuple = [oldValue: bigint, newValue: bigint];
  export interface OutputObject {
    oldValue: bigint;
    newValue: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MaxBidsPerIterationUpdatedEvent {
  export type InputTuple = [oldValue: BigNumberish, newValue: BigNumberish];
  export type OutputTuple = [oldValue: bigint, newValue: bigint];
  export interface OutputObject {
    oldValue: bigint;
    newValue: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MaxContractsPerUserUpdatedEvent {
  export type InputTuple = [oldValue: BigNumberish, newValue: BigNumberish];
  export type OutputTuple = [oldValue: bigint, newValue: bigint];
  export interface OutputObject {
    oldValue: bigint;
    newValue: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MaxUserFundsUpdatedEvent {
  export type InputTuple = [oldValue: BigNumberish, newValue: BigNumberish];
  export type OutputTuple = [oldValue: bigint, newValue: bigint];
  export interface OutputObject {
    oldValue: bigint;
    newValue: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MaxUsersPerPageUpdatedEvent {
  export type InputTuple = [oldValue: BigNumberish, newValue: BigNumberish];
  export type OutputTuple = [oldValue: bigint, newValue: bigint];
  export interface OutputObject {
    oldValue: bigint;
    newValue: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MinBidCheckEvent {
  export type InputTuple = [contractAddress: AddressLike, minBid: BigNumberish];
  export type OutputTuple = [contractAddress: string, minBid: bigint];
  export interface OutputObject {
    contractAddress: string;
    minBid: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MinFundAmountUpdatedEvent {
  export type InputTuple = [oldValue: BigNumberish, newValue: BigNumberish];
  export type OutputTuple = [oldValue: bigint, newValue: bigint];
  export interface OutputObject {
    oldValue: bigint;
    newValue: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MinMaxBidAmountUpdatedEvent {
  export type InputTuple = [oldValue: BigNumberish, newValue: BigNumberish];
  export type OutputTuple = [oldValue: bigint, newValue: bigint];
  export interface OutputObject {
    oldValue: bigint;
    newValue: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpkeepPerformedEvent {
  export type InputTuple = [
    totalContracts: BigNumberish,
    successfulBids: BigNumberish,
    failedBids: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    totalContracts: bigint,
    successfulBids: bigint,
    failedBids: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    totalContracts: bigint;
    successfulBids: bigint;
    failedBids: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserBalanceOperationEvent {
  export type InputTuple = [
    user: AddressLike,
    operation: string,
    amount: BigNumberish,
    newBalance: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    operation: string,
    amount: bigint,
    newBalance: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    user: string;
    operation: string;
    amount: bigint;
    newBalance: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CacheManagerAutomation extends BaseContract {
  connect(runner?: ContractRunner | null): CacheManagerAutomation;
  waitForDeployment(): Promise<this>;

  interface: CacheManagerAutomationInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  arbWasm: TypedContractMethod<[], [string], "view">;

  arbWasmCache: TypedContractMethod<[], [string], "view">;

  bidIncrement: TypedContractMethod<[], [bigint], "view">;

  cacheManager: TypedContractMethod<[], [string], "view">;

  cacheThreshold: TypedContractMethod<[], [bigint], "view">;

  escrow: TypedContractMethod<[], [string], "view">;

  fundBalance: TypedContractMethod<[], [void], "payable">;

  getContracts: TypedContractMethod<
    [],
    [ICacheManagerAutomation.UserContractsDataStructOutput[]],
    "view"
  >;

  getContractsPaginated: TypedContractMethod<
    [offset: BigNumberish, limit: BigNumberish],
    [
      [ICacheManagerAutomation.UserContractsDataStructOutput[], boolean] & {
        userData: ICacheManagerAutomation.UserContractsDataStructOutput[];
        hasMore: boolean;
      }
    ],
    "view"
  >;

  getTotalUsersCount: TypedContractMethod<[], [bigint], "view">;

  getUserAtIndex: TypedContractMethod<[index: BigNumberish], [string], "view">;

  getUserBalance: TypedContractMethod<[], [bigint], "view">;

  getUserContracts: TypedContractMethod<
    [],
    [ICacheManagerAutomation.ContractConfigStructOutput[]],
    "view"
  >;

  horizonSeconds: TypedContractMethod<[], [bigint], "view">;

  insertContract: TypedContractMethod<
    [
      _contract: AddressLike,
      _maxBid: BigNumberish,
      _enabled: boolean,
      _autoActivate: boolean,
      _maxActivationCost: BigNumberish
    ],
    [void],
    "payable"
  >;

  maxActivationsPerIteration: TypedContractMethod<[], [bigint], "view">;

  maxBidsPerIteration: TypedContractMethod<[], [bigint], "view">;

  maxContractsPerUser: TypedContractMethod<[], [bigint], "view">;

  maxUserFunds: TypedContractMethod<[], [bigint], "view">;

  maxUsersPerPage: TypedContractMethod<[], [bigint], "view">;

  minFundAmount: TypedContractMethod<[], [bigint], "view">;

  minMaxBidAmount: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  placeActivations: TypedContractMethod<
    [_activationRequests: ICacheManagerAutomation.ActivationRequestStruct[]],
    [void],
    "nonpayable"
  >;

  placeBids: TypedContractMethod<
    [_bidRequests: ICacheManagerAutomation.BidRequestStruct[]],
    [void],
    "nonpayable"
  >;

  removeAllContracts: TypedContractMethod<[], [void], "nonpayable">;

  removeContract: TypedContractMethod<
    [_contract: AddressLike],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setBidIncrement: TypedContractMethod<
    [_bidIncrement: BigNumberish],
    [void],
    "nonpayable"
  >;

  setCacheThreshold: TypedContractMethod<
    [_cacheThreshold: BigNumberish],
    [void],
    "nonpayable"
  >;

  setHorizonSeconds: TypedContractMethod<
    [_horizonSeconds: BigNumberish],
    [void],
    "nonpayable"
  >;

  setMaxActivationsPerIteration: TypedContractMethod<
    [_maxActivationsPerIteration: BigNumberish],
    [void],
    "nonpayable"
  >;

  setMaxBidsPerIteration: TypedContractMethod<
    [_maxBidsPerIteration: BigNumberish],
    [void],
    "nonpayable"
  >;

  setMaxContractsPerUser: TypedContractMethod<
    [_maxContractsPerUser: BigNumberish],
    [void],
    "nonpayable"
  >;

  setMaxUserFunds: TypedContractMethod<
    [_maxUserFunds: BigNumberish],
    [void],
    "nonpayable"
  >;

  setMaxUsersPerPage: TypedContractMethod<
    [_maxUsersPerPage: BigNumberish],
    [void],
    "nonpayable"
  >;

  setMinFundAmount: TypedContractMethod<
    [_minFundAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  setMinMaxBidAmount: TypedContractMethod<
    [_minMaxBidAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateContract: TypedContractMethod<
    [
      _contract: AddressLike,
      _maxBid: BigNumberish,
      _enabled: boolean,
      _autoActivate: boolean,
      _maxActivationCost: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  userContracts: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [string, bigint, boolean, boolean, bigint] & {
        contractAddress: string;
        maxBid: bigint;
        enabled: boolean;
        autoActivate: boolean;
        maxActivationCost: bigint;
      }
    ],
    "view"
  >;

  withdrawBalance: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "arbWasm"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "arbWasmCache"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "bidIncrement"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "cacheManager"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "cacheThreshold"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "escrow"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "fundBalance"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "getContracts"
  ): TypedContractMethod<
    [],
    [ICacheManagerAutomation.UserContractsDataStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getContractsPaginated"
  ): TypedContractMethod<
    [offset: BigNumberish, limit: BigNumberish],
    [
      [ICacheManagerAutomation.UserContractsDataStructOutput[], boolean] & {
        userData: ICacheManagerAutomation.UserContractsDataStructOutput[];
        hasMore: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTotalUsersCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserAtIndex"
  ): TypedContractMethod<[index: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getUserBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserContracts"
  ): TypedContractMethod<
    [],
    [ICacheManagerAutomation.ContractConfigStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "horizonSeconds"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "insertContract"
  ): TypedContractMethod<
    [
      _contract: AddressLike,
      _maxBid: BigNumberish,
      _enabled: boolean,
      _autoActivate: boolean,
      _maxActivationCost: BigNumberish
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "maxActivationsPerIteration"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "maxBidsPerIteration"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "maxContractsPerUser"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "maxUserFunds"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "maxUsersPerPage"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "minFundAmount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "minMaxBidAmount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "placeActivations"
  ): TypedContractMethod<
    [_activationRequests: ICacheManagerAutomation.ActivationRequestStruct[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "placeBids"
  ): TypedContractMethod<
    [_bidRequests: ICacheManagerAutomation.BidRequestStruct[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "removeAllContracts"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "removeContract"
  ): TypedContractMethod<[_contract: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setBidIncrement"
  ): TypedContractMethod<[_bidIncrement: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setCacheThreshold"
  ): TypedContractMethod<[_cacheThreshold: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setHorizonSeconds"
  ): TypedContractMethod<[_horizonSeconds: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMaxActivationsPerIteration"
  ): TypedContractMethod<
    [_maxActivationsPerIteration: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setMaxBidsPerIteration"
  ): TypedContractMethod<
    [_maxBidsPerIteration: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setMaxContractsPerUser"
  ): TypedContractMethod<
    [_maxContractsPerUser: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setMaxUserFunds"
  ): TypedContractMethod<[_maxUserFunds: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMaxUsersPerPage"
  ): TypedContractMethod<
    [_maxUsersPerPage: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setMinFundAmount"
  ): TypedContractMethod<[_minFundAmount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMinMaxBidAmount"
  ): TypedContractMethod<
    [_minMaxBidAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateContract"
  ): TypedContractMethod<
    [
      _contract: AddressLike,
      _maxBid: BigNumberish,
      _enabled: boolean,
      _autoActivate: boolean,
      _maxActivationCost: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "userContracts"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [string, bigint, boolean, boolean, bigint] & {
        contractAddress: string;
        maxBid: bigint;
        enabled: boolean;
        autoActivate: boolean;
        maxActivationCost: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "withdrawBalance"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "ActivationError"
  ): TypedContractEvent<
    ActivationErrorEvent.InputTuple,
    ActivationErrorEvent.OutputTuple,
    ActivationErrorEvent.OutputObject
  >;
  getEvent(
    key: "ActivationPerformed"
  ): TypedContractEvent<
    ActivationPerformedEvent.InputTuple,
    ActivationPerformedEvent.OutputTuple,
    ActivationPerformedEvent.OutputObject
  >;
  getEvent(
    key: "ActivationRevertData"
  ): TypedContractEvent<
    ActivationRevertDataEvent.InputTuple,
    ActivationRevertDataEvent.OutputTuple,
    ActivationRevertDataEvent.OutputObject
  >;
  getEvent(
    key: "BalanceUpdated"
  ): TypedContractEvent<
    BalanceUpdatedEvent.InputTuple,
    BalanceUpdatedEvent.OutputTuple,
    BalanceUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "BidAttempted"
  ): TypedContractEvent<
    BidAttemptedEvent.InputTuple,
    BidAttemptedEvent.OutputTuple,
    BidAttemptedEvent.OutputObject
  >;
  getEvent(
    key: "BidDetails"
  ): TypedContractEvent<
    BidDetailsEvent.InputTuple,
    BidDetailsEvent.OutputTuple,
    BidDetailsEvent.OutputObject
  >;
  getEvent(
    key: "BidError"
  ): TypedContractEvent<
    BidErrorEvent.InputTuple,
    BidErrorEvent.OutputTuple,
    BidErrorEvent.OutputObject
  >;
  getEvent(
    key: "BidIncrementUpdated"
  ): TypedContractEvent<
    BidIncrementUpdatedEvent.InputTuple,
    BidIncrementUpdatedEvent.OutputTuple,
    BidIncrementUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "BidPlaced"
  ): TypedContractEvent<
    BidPlacedEvent.InputTuple,
    BidPlacedEvent.OutputTuple,
    BidPlacedEvent.OutputObject
  >;
  getEvent(
    key: "CacheThresholdUpdated"
  ): TypedContractEvent<
    CacheThresholdUpdatedEvent.InputTuple,
    CacheThresholdUpdatedEvent.OutputTuple,
    CacheThresholdUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ContractAdded"
  ): TypedContractEvent<
    ContractAddedEvent.InputTuple,
    ContractAddedEvent.OutputTuple,
    ContractAddedEvent.OutputObject
  >;
  getEvent(
    key: "ContractAutoActivateUpdated"
  ): TypedContractEvent<
    ContractAutoActivateUpdatedEvent.InputTuple,
    ContractAutoActivateUpdatedEvent.OutputTuple,
    ContractAutoActivateUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ContractMaxActivationCostUpdated"
  ): TypedContractEvent<
    ContractMaxActivationCostUpdatedEvent.InputTuple,
    ContractMaxActivationCostUpdatedEvent.OutputTuple,
    ContractMaxActivationCostUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ContractOperationPerformed"
  ): TypedContractEvent<
    ContractOperationPerformedEvent.InputTuple,
    ContractOperationPerformedEvent.OutputTuple,
    ContractOperationPerformedEvent.OutputObject
  >;
  getEvent(
    key: "ContractRemoved"
  ): TypedContractEvent<
    ContractRemovedEvent.InputTuple,
    ContractRemovedEvent.OutputTuple,
    ContractRemovedEvent.OutputObject
  >;
  getEvent(
    key: "ContractUpdated"
  ): TypedContractEvent<
    ContractUpdatedEvent.InputTuple,
    ContractUpdatedEvent.OutputTuple,
    ContractUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "DebugBidCheck"
  ): TypedContractEvent<
    DebugBidCheckEvent.InputTuple,
    DebugBidCheckEvent.OutputTuple,
    DebugBidCheckEvent.OutputObject
  >;
  getEvent(
    key: "DebugMinBidFetch"
  ): TypedContractEvent<
    DebugMinBidFetchEvent.InputTuple,
    DebugMinBidFetchEvent.OutputTuple,
    DebugMinBidFetchEvent.OutputObject
  >;
  getEvent(
    key: "HorizonSecondsUpdated"
  ): TypedContractEvent<
    HorizonSecondsUpdatedEvent.InputTuple,
    HorizonSecondsUpdatedEvent.OutputTuple,
    HorizonSecondsUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "MaxActivationsPerIterationUpdated"
  ): TypedContractEvent<
    MaxActivationsPerIterationUpdatedEvent.InputTuple,
    MaxActivationsPerIterationUpdatedEvent.OutputTuple,
    MaxActivationsPerIterationUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "MaxBidsPerIterationUpdated"
  ): TypedContractEvent<
    MaxBidsPerIterationUpdatedEvent.InputTuple,
    MaxBidsPerIterationUpdatedEvent.OutputTuple,
    MaxBidsPerIterationUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "MaxContractsPerUserUpdated"
  ): TypedContractEvent<
    MaxContractsPerUserUpdatedEvent.InputTuple,
    MaxContractsPerUserUpdatedEvent.OutputTuple,
    MaxContractsPerUserUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "MaxUserFundsUpdated"
  ): TypedContractEvent<
    MaxUserFundsUpdatedEvent.InputTuple,
    MaxUserFundsUpdatedEvent.OutputTuple,
    MaxUserFundsUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "MaxUsersPerPageUpdated"
  ): TypedContractEvent<
    MaxUsersPerPageUpdatedEvent.InputTuple,
    MaxUsersPerPageUpdatedEvent.OutputTuple,
    MaxUsersPerPageUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "MinBidCheck"
  ): TypedContractEvent<
    MinBidCheckEvent.InputTuple,
    MinBidCheckEvent.OutputTuple,
    MinBidCheckEvent.OutputObject
  >;
  getEvent(
    key: "MinFundAmountUpdated"
  ): TypedContractEvent<
    MinFundAmountUpdatedEvent.InputTuple,
    MinFundAmountUpdatedEvent.OutputTuple,
    MinFundAmountUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "MinMaxBidAmountUpdated"
  ): TypedContractEvent<
    MinMaxBidAmountUpdatedEvent.InputTuple,
    MinMaxBidAmountUpdatedEvent.OutputTuple,
    MinMaxBidAmountUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;
  getEvent(
    key: "UpkeepPerformed"
  ): TypedContractEvent<
    UpkeepPerformedEvent.InputTuple,
    UpkeepPerformedEvent.OutputTuple,
    UpkeepPerformedEvent.OutputObject
  >;
  getEvent(
    key: "UserBalanceOperation"
  ): TypedContractEvent<
    UserBalanceOperationEvent.InputTuple,
    UserBalanceOperationEvent.OutputTuple,
    UserBalanceOperationEvent.OutputObject
  >;

  filters: {
    "ActivationError(address,address,uint256,string)": TypedContractEvent<
      ActivationErrorEvent.InputTuple,
      ActivationErrorEvent.OutputTuple,
      ActivationErrorEvent.OutputObject
    >;
    ActivationError: TypedContractEvent<
      ActivationErrorEvent.InputTuple,
      ActivationErrorEvent.OutputTuple,
      ActivationErrorEvent.OutputObject
    >;

    "ActivationPerformed(address,address,uint16,uint256,uint256,uint256,uint256)": TypedContractEvent<
      ActivationPerformedEvent.InputTuple,
      ActivationPerformedEvent.OutputTuple,
      ActivationPerformedEvent.OutputObject
    >;
    ActivationPerformed: TypedContractEvent<
      ActivationPerformedEvent.InputTuple,
      ActivationPerformedEvent.OutputTuple,
      ActivationPerformedEvent.OutputObject
    >;

    "ActivationRevertData(address,address,bytes)": TypedContractEvent<
      ActivationRevertDataEvent.InputTuple,
      ActivationRevertDataEvent.OutputTuple,
      ActivationRevertDataEvent.OutputObject
    >;
    ActivationRevertData: TypedContractEvent<
      ActivationRevertDataEvent.InputTuple,
      ActivationRevertDataEvent.OutputTuple,
      ActivationRevertDataEvent.OutputObject
    >;

    "BalanceUpdated(address,uint256)": TypedContractEvent<
      BalanceUpdatedEvent.InputTuple,
      BalanceUpdatedEvent.OutputTuple,
      BalanceUpdatedEvent.OutputObject
    >;
    BalanceUpdated: TypedContractEvent<
      BalanceUpdatedEvent.InputTuple,
      BalanceUpdatedEvent.OutputTuple,
      BalanceUpdatedEvent.OutputObject
    >;

    "BidAttempted(address,address,uint256,bool)": TypedContractEvent<
      BidAttemptedEvent.InputTuple,
      BidAttemptedEvent.OutputTuple,
      BidAttemptedEvent.OutputObject
    >;
    BidAttempted: TypedContractEvent<
      BidAttemptedEvent.InputTuple,
      BidAttemptedEvent.OutputTuple,
      BidAttemptedEvent.OutputObject
    >;

    "BidDetails(address,address,uint256,uint256,uint256,uint256,bool)": TypedContractEvent<
      BidDetailsEvent.InputTuple,
      BidDetailsEvent.OutputTuple,
      BidDetailsEvent.OutputObject
    >;
    BidDetails: TypedContractEvent<
      BidDetailsEvent.InputTuple,
      BidDetailsEvent.OutputTuple,
      BidDetailsEvent.OutputObject
    >;

    "BidError(address,address,uint256,string)": TypedContractEvent<
      BidErrorEvent.InputTuple,
      BidErrorEvent.OutputTuple,
      BidErrorEvent.OutputObject
    >;
    BidError: TypedContractEvent<
      BidErrorEvent.InputTuple,
      BidErrorEvent.OutputTuple,
      BidErrorEvent.OutputObject
    >;

    "BidIncrementUpdated(uint192,uint192)": TypedContractEvent<
      BidIncrementUpdatedEvent.InputTuple,
      BidIncrementUpdatedEvent.OutputTuple,
      BidIncrementUpdatedEvent.OutputObject
    >;
    BidIncrementUpdated: TypedContractEvent<
      BidIncrementUpdatedEvent.InputTuple,
      BidIncrementUpdatedEvent.OutputTuple,
      BidIncrementUpdatedEvent.OutputObject
    >;

    "BidPlaced(address,address,uint256,uint256,uint256)": TypedContractEvent<
      BidPlacedEvent.InputTuple,
      BidPlacedEvent.OutputTuple,
      BidPlacedEvent.OutputObject
    >;
    BidPlaced: TypedContractEvent<
      BidPlacedEvent.InputTuple,
      BidPlacedEvent.OutputTuple,
      BidPlacedEvent.OutputObject
    >;

    "CacheThresholdUpdated(uint256,uint256)": TypedContractEvent<
      CacheThresholdUpdatedEvent.InputTuple,
      CacheThresholdUpdatedEvent.OutputTuple,
      CacheThresholdUpdatedEvent.OutputObject
    >;
    CacheThresholdUpdated: TypedContractEvent<
      CacheThresholdUpdatedEvent.InputTuple,
      CacheThresholdUpdatedEvent.OutputTuple,
      CacheThresholdUpdatedEvent.OutputObject
    >;

    "ContractAdded(address,address,uint256)": TypedContractEvent<
      ContractAddedEvent.InputTuple,
      ContractAddedEvent.OutputTuple,
      ContractAddedEvent.OutputObject
    >;
    ContractAdded: TypedContractEvent<
      ContractAddedEvent.InputTuple,
      ContractAddedEvent.OutputTuple,
      ContractAddedEvent.OutputObject
    >;

    "ContractAutoActivateUpdated(address,address,bool)": TypedContractEvent<
      ContractAutoActivateUpdatedEvent.InputTuple,
      ContractAutoActivateUpdatedEvent.OutputTuple,
      ContractAutoActivateUpdatedEvent.OutputObject
    >;
    ContractAutoActivateUpdated: TypedContractEvent<
      ContractAutoActivateUpdatedEvent.InputTuple,
      ContractAutoActivateUpdatedEvent.OutputTuple,
      ContractAutoActivateUpdatedEvent.OutputObject
    >;

    "ContractMaxActivationCostUpdated(address,address,uint256)": TypedContractEvent<
      ContractMaxActivationCostUpdatedEvent.InputTuple,
      ContractMaxActivationCostUpdatedEvent.OutputTuple,
      ContractMaxActivationCostUpdatedEvent.OutputObject
    >;
    ContractMaxActivationCostUpdated: TypedContractEvent<
      ContractMaxActivationCostUpdatedEvent.InputTuple,
      ContractMaxActivationCostUpdatedEvent.OutputTuple,
      ContractMaxActivationCostUpdatedEvent.OutputObject
    >;

    "ContractOperationPerformed(address,address,string,uint256)": TypedContractEvent<
      ContractOperationPerformedEvent.InputTuple,
      ContractOperationPerformedEvent.OutputTuple,
      ContractOperationPerformedEvent.OutputObject
    >;
    ContractOperationPerformed: TypedContractEvent<
      ContractOperationPerformedEvent.InputTuple,
      ContractOperationPerformedEvent.OutputTuple,
      ContractOperationPerformedEvent.OutputObject
    >;

    "ContractRemoved(address,address)": TypedContractEvent<
      ContractRemovedEvent.InputTuple,
      ContractRemovedEvent.OutputTuple,
      ContractRemovedEvent.OutputObject
    >;
    ContractRemoved: TypedContractEvent<
      ContractRemovedEvent.InputTuple,
      ContractRemovedEvent.OutputTuple,
      ContractRemovedEvent.OutputObject
    >;

    "ContractUpdated(address,address,uint256)": TypedContractEvent<
      ContractUpdatedEvent.InputTuple,
      ContractUpdatedEvent.OutputTuple,
      ContractUpdatedEvent.OutputObject
    >;
    ContractUpdated: TypedContractEvent<
      ContractUpdatedEvent.InputTuple,
      ContractUpdatedEvent.OutputTuple,
      ContractUpdatedEvent.OutputObject
    >;

    "DebugBidCheck(address,address,string)": TypedContractEvent<
      DebugBidCheckEvent.InputTuple,
      DebugBidCheckEvent.OutputTuple,
      DebugBidCheckEvent.OutputObject
    >;
    DebugBidCheck: TypedContractEvent<
      DebugBidCheckEvent.InputTuple,
      DebugBidCheckEvent.OutputTuple,
      DebugBidCheckEvent.OutputObject
    >;

    "DebugMinBidFetch(address,uint192,bool)": TypedContractEvent<
      DebugMinBidFetchEvent.InputTuple,
      DebugMinBidFetchEvent.OutputTuple,
      DebugMinBidFetchEvent.OutputObject
    >;
    DebugMinBidFetch: TypedContractEvent<
      DebugMinBidFetchEvent.InputTuple,
      DebugMinBidFetchEvent.OutputTuple,
      DebugMinBidFetchEvent.OutputObject
    >;

    "HorizonSecondsUpdated(uint256,uint256)": TypedContractEvent<
      HorizonSecondsUpdatedEvent.InputTuple,
      HorizonSecondsUpdatedEvent.OutputTuple,
      HorizonSecondsUpdatedEvent.OutputObject
    >;
    HorizonSecondsUpdated: TypedContractEvent<
      HorizonSecondsUpdatedEvent.InputTuple,
      HorizonSecondsUpdatedEvent.OutputTuple,
      HorizonSecondsUpdatedEvent.OutputObject
    >;

    "MaxActivationsPerIterationUpdated(uint256,uint256)": TypedContractEvent<
      MaxActivationsPerIterationUpdatedEvent.InputTuple,
      MaxActivationsPerIterationUpdatedEvent.OutputTuple,
      MaxActivationsPerIterationUpdatedEvent.OutputObject
    >;
    MaxActivationsPerIterationUpdated: TypedContractEvent<
      MaxActivationsPerIterationUpdatedEvent.InputTuple,
      MaxActivationsPerIterationUpdatedEvent.OutputTuple,
      MaxActivationsPerIterationUpdatedEvent.OutputObject
    >;

    "MaxBidsPerIterationUpdated(uint256,uint256)": TypedContractEvent<
      MaxBidsPerIterationUpdatedEvent.InputTuple,
      MaxBidsPerIterationUpdatedEvent.OutputTuple,
      MaxBidsPerIterationUpdatedEvent.OutputObject
    >;
    MaxBidsPerIterationUpdated: TypedContractEvent<
      MaxBidsPerIterationUpdatedEvent.InputTuple,
      MaxBidsPerIterationUpdatedEvent.OutputTuple,
      MaxBidsPerIterationUpdatedEvent.OutputObject
    >;

    "MaxContractsPerUserUpdated(uint256,uint256)": TypedContractEvent<
      MaxContractsPerUserUpdatedEvent.InputTuple,
      MaxContractsPerUserUpdatedEvent.OutputTuple,
      MaxContractsPerUserUpdatedEvent.OutputObject
    >;
    MaxContractsPerUserUpdated: TypedContractEvent<
      MaxContractsPerUserUpdatedEvent.InputTuple,
      MaxContractsPerUserUpdatedEvent.OutputTuple,
      MaxContractsPerUserUpdatedEvent.OutputObject
    >;

    "MaxUserFundsUpdated(uint256,uint256)": TypedContractEvent<
      MaxUserFundsUpdatedEvent.InputTuple,
      MaxUserFundsUpdatedEvent.OutputTuple,
      MaxUserFundsUpdatedEvent.OutputObject
    >;
    MaxUserFundsUpdated: TypedContractEvent<
      MaxUserFundsUpdatedEvent.InputTuple,
      MaxUserFundsUpdatedEvent.OutputTuple,
      MaxUserFundsUpdatedEvent.OutputObject
    >;

    "MaxUsersPerPageUpdated(uint256,uint256)": TypedContractEvent<
      MaxUsersPerPageUpdatedEvent.InputTuple,
      MaxUsersPerPageUpdatedEvent.OutputTuple,
      MaxUsersPerPageUpdatedEvent.OutputObject
    >;
    MaxUsersPerPageUpdated: TypedContractEvent<
      MaxUsersPerPageUpdatedEvent.InputTuple,
      MaxUsersPerPageUpdatedEvent.OutputTuple,
      MaxUsersPerPageUpdatedEvent.OutputObject
    >;

    "MinBidCheck(address,uint256)": TypedContractEvent<
      MinBidCheckEvent.InputTuple,
      MinBidCheckEvent.OutputTuple,
      MinBidCheckEvent.OutputObject
    >;
    MinBidCheck: TypedContractEvent<
      MinBidCheckEvent.InputTuple,
      MinBidCheckEvent.OutputTuple,
      MinBidCheckEvent.OutputObject
    >;

    "MinFundAmountUpdated(uint256,uint256)": TypedContractEvent<
      MinFundAmountUpdatedEvent.InputTuple,
      MinFundAmountUpdatedEvent.OutputTuple,
      MinFundAmountUpdatedEvent.OutputObject
    >;
    MinFundAmountUpdated: TypedContractEvent<
      MinFundAmountUpdatedEvent.InputTuple,
      MinFundAmountUpdatedEvent.OutputTuple,
      MinFundAmountUpdatedEvent.OutputObject
    >;

    "MinMaxBidAmountUpdated(uint256,uint256)": TypedContractEvent<
      MinMaxBidAmountUpdatedEvent.InputTuple,
      MinMaxBidAmountUpdatedEvent.OutputTuple,
      MinMaxBidAmountUpdatedEvent.OutputObject
    >;
    MinMaxBidAmountUpdated: TypedContractEvent<
      MinMaxBidAmountUpdatedEvent.InputTuple,
      MinMaxBidAmountUpdatedEvent.OutputTuple,
      MinMaxBidAmountUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;

    "UpkeepPerformed(uint256,uint256,uint256,uint256)": TypedContractEvent<
      UpkeepPerformedEvent.InputTuple,
      UpkeepPerformedEvent.OutputTuple,
      UpkeepPerformedEvent.OutputObject
    >;
    UpkeepPerformed: TypedContractEvent<
      UpkeepPerformedEvent.InputTuple,
      UpkeepPerformedEvent.OutputTuple,
      UpkeepPerformedEvent.OutputObject
    >;

    "UserBalanceOperation(address,string,uint256,uint256,uint256)": TypedContractEvent<
      UserBalanceOperationEvent.InputTuple,
      UserBalanceOperationEvent.OutputTuple,
      UserBalanceOperationEvent.OutputObject
    >;
    UserBalanceOperation: TypedContractEvent<
      UserBalanceOperationEvent.InputTuple,
      UserBalanceOperationEvent.OutputTuple,
      UserBalanceOperationEvent.OutputObject
    >;
  };
}
